id: og_image
key: og_image
name: og_image content クリエイター
version: 0.03
description: og_image の content を自動的に作成します
author_name: Hatsuhito UENO A.K.A. uehatsu
author_link: http://uehatsu.info

system_config_template: og_image_settings.tmpl
settings:
    og_image_default_path:
        default: /mt-static/images/bug-pbmt-white.png
        scope: system
    og_image_min_size:
        default: 180
        scope: system

tags:
    function:
        OgImageTag: $og_image::og_image::hdlr_og_image_content
